//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiscalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int userID { get; set; }
        public string category { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateOfPurchase { get; set; }
    }
}
